In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import cv2
import matplotlib.pyplot as plt
from sys import getsizeof
import gc
%matplotlib inline

In [2]:
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model 
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D, Conv2D, Activation, MaxPooling2D
from keras import backend as k 
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping, ReduceLROnPlateau
from keras.applications.resnet50 import preprocess_input

Using TensorFlow backend.


In [3]:
base_model = applications.ResNet50(include_top=False, weights='imagenet', input_tensor=None, input_shape=(200,200,3), pooling=None)


In [4]:
base_model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 200, 200, 3)  0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 100, 100, 64) 9472        input_1[0][0]                    
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 100, 100, 64) 256         conv1[0][0]                      
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 100, 100, 64) 0           bn_conv1[0][0]                   
__________________________________________________________________________________________________
max_poolin

In [5]:
for layer in base_model.layers[:-75]:
     layer.trainable = False

In [6]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(512,activation='relu')(x)
x = Dense(8, activation='softmax')(x)
model = Model(base_model.input, x)

In [7]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 200, 200, 3)  0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 100, 100, 64) 9472        input_1[0][0]                    
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 100, 100, 64) 256         conv1[0][0]                      
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 100, 100, 64) 0           bn_conv1[0][0]                   
__________________________________________________________________________________________________
max_poolin

In [8]:
from keras import metrics
def top_2_accuracy(y_true, y_pred):
    return metrics.top_k_categorical_accuracy(y_true, y_pred, k=2)
    

In [9]:
adam = optimizers.Adam(lr=0.0001,beta_1=0.9, beta_2=0.999, epsilon=k.epsilon(), decay=0.0)

In [10]:
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy',top_2_accuracy])

In [11]:
reduce_lr = ReduceLROnPlateau(monitor='val_loss',factor = 0.5,patience = 1, min_lr = 0.00001, verbose = 1)

In [12]:
train_directory = "Images/train_images_cropped_downsampled"
t_size = (200, 200)
b_size = 16
test_directory = "Images/validation_images_cropped_downsampled"

In [24]:
train_gen = ImageDataGenerator(
preprocessing_function=preprocess_input,
horizontal_flip = True,
rotation_range = 30,
zoom_range = 0.2)

test_gen = ImageDataGenerator(
preprocessing_function=preprocess_input,
horizontal_flip = True)

train_generator = train_gen.flow_from_directory(
train_directory,
target_size = t_size,
batch_size = b_size,
class_mode = "categorical")

validation_generator = test_gen.flow_from_directory(
test_directory,
target_size = t_size,
batch_size = b_size,
class_mode = "categorical")



Found 61136 images belonging to 8 classes.
Found 800 images belonging to 8 classes.


In [14]:
checkpoint = ModelCheckpoint(filepath='saved_models/model.weights.best.down_sampled_3101.{epoch:02d}-{val_loss:.2f}.hdf5', verbose=1, save_best_only=True)

In [15]:
history7 = model.fit_generator(train_generator, epochs=10, validation_data=validation_generator, verbose=2, 
                               callbacks=[checkpoint,reduce_lr], steps_per_epoch=3821, validation_steps=50)

Epoch 1/10
Epoch 00001: val_loss improved from inf to 1.46089, saving model to saved_models/model.weights.best.down_sampled_3101.01-1.46.hdf5
 - 1403s - loss: 1.3412 - acc: 0.5058 - top_2_accuracy: 0.7161 - val_loss: 1.4609 - val_acc: 0.4612 - val_top_2_accuracy: 0.6975
Epoch 2/10
Epoch 00002: val_loss improved from 1.46089 to 1.42816, saving model to saved_models/model.weights.best.down_sampled_3101.02-1.43.hdf5
 - 1381s - loss: 1.1635 - acc: 0.5697 - top_2_accuracy: 0.7759 - val_loss: 1.4282 - val_acc: 0.4662 - val_top_2_accuracy: 0.7087
Epoch 3/10
Epoch 00003: val_loss improved from 1.42816 to 1.39946, saving model to saved_models/model.weights.best.down_sampled_3101.03-1.40.hdf5
 - 1382s - loss: 1.0971 - acc: 0.5936 - top_2_accuracy: 0.7966 - val_loss: 1.3995 - val_acc: 0.4863 - val_top_2_accuracy: 0.7087
Epoch 4/10
Epoch 00004: val_loss did not improve
 - 1380s - loss: 1.0572 - acc: 0.6102 - top_2_accuracy: 0.8079 - val_loss: 1.4317 - val_acc: 0.4763 - val_top_2_accuracy: 0.7300
E

In [14]:
checkpoint = ModelCheckpoint(filepath='saved_models/model.weights.best.down_sampled_0102.{epoch:02d}-{val_acc:.2f}.hdf5', verbose=1, save_best_only=True)

In [15]:
history8 = model.fit_generator(train_generator, epochs=15, validation_data=validation_generator, verbose=2, 
                               callbacks=[checkpoint,reduce_lr], steps_per_epoch=3821, validation_steps=50)

Epoch 1/15
Epoch 00001: val_loss improved from inf to 1.54794, saving model to saved_models/model.weights.best.down_sampled_0102.01-0.45.hdf5
 - 1400s - loss: 1.3408 - acc: 0.5035 - top_2_accuracy: 0.7158 - val_loss: 1.5479 - val_acc: 0.4500 - val_top_2_accuracy: 0.6800
Epoch 2/15
Epoch 00002: val_loss improved from 1.54794 to 1.47615, saving model to saved_models/model.weights.best.down_sampled_0102.02-0.45.hdf5
 - 1381s - loss: 1.1628 - acc: 0.5708 - top_2_accuracy: 0.7759 - val_loss: 1.4762 - val_acc: 0.4537 - val_top_2_accuracy: 0.6875
Epoch 3/15
Epoch 00003: val_loss improved from 1.47615 to 1.37216, saving model to saved_models/model.weights.best.down_sampled_0102.03-0.51.hdf5
 - 1381s - loss: 1.0986 - acc: 0.5946 - top_2_accuracy: 0.7980 - val_loss: 1.3722 - val_acc: 0.5050 - val_top_2_accuracy: 0.7312
Epoch 4/15
Epoch 00004: val_loss did not improve
 - 1384s - loss: 1.0538 - acc: 0.6104 - top_2_accuracy: 0.8119 - val_loss: 1.4014 - val_acc: 0.5125 - val_top_2_accuracy: 0.7025
E

In [13]:
#now testing on full validation data making use of different performance measure
#first loading the weights from previously saved models
model.load_weights(filepath="saved_models/model.weights.best.down_sampled_3101.08-1.34.hdf5")

In [14]:
full_validation_gen = ImageDataGenerator(preprocessing_function=preprocess_input)
full_validation_generator = full_validation_gen.flow_from_directory(
"Images/full_validation",
target_size = t_size,
batch_size = 1,
class_mode=None,
shuffle=False)

Found 3999 images belonging to 1 classes.


In [15]:
#now do the prediction
predictions = model.predict_generator(full_validation_generator,steps=3999)

In [29]:
top_1_pred = []
for i in predictions:
    top_1_pred.append(np.argmax(i))
top_1_pred = np.array(top_1_pred)

In [30]:
top_2_pred = []
for i in predictions:
    top_2_pred.append(np.argpartition(i,-2)[-2:])
top_2_pred = np.array(top_2_pred)

In [31]:
top_2_pred

array([[7, 1],
       [5, 6],
       [5, 6],
       ..., 
       [4, 3],
       [4, 6],
       [4, 3]], dtype=int64)

In [17]:
full_validation_set = pd.read_csv("datasets/full_validation_set.csv")

In [18]:
full_validation_set = full_validation_set.drop('Unnamed: 0',axis=1)

In [19]:
full_validation_set

subDirectory_filePath  face_x  face_y  \
0     328/7dc825b5a55f0c7a877773868b883c550f513efdcb...      24      24   
1     427/0bc723f0a6a0cb33a4ae1ca53f203ff14d790e6e8b...     119     119   
2     874/24c566d363e0f05a6df344804a705957a71e2d1870...      46      46   
3     357/0af4eb252fe5dcf012229787b52fa2bdfe65e7e9fa...      88      88   
4     481/ffba2d1395dcfe3f2a81850cbc1525f34969ec0789...      77      77   
5     854/14558b183e1db89777afef50f22e2cb461b6567f41...      82      82   
6     462/bb8fd77a0cd112dc280bcf90eb02d13e745d9a1d95...      91      91   
7     493/67ed933f3336366a3c9fa8dd1b6d8cfc2fdf446632...      13      13   
8     849/1b95b83aadd670c369da4184ae0dac4aa7994c16e7...      29      29   
9     518/a990be317b7b4741996554770ff1045b64574c99c3...      31      31   
10    740/2f4dedf79df530f1077aeab3938a38a9ceb95f23af...      26      26   
11    1058/b7275891d8daf1791ed57311487fcdb34ad57abe9...      36      36   
12    1320/d6a50e49924f86a031f30d3387ac19bcdaee18f67...      23      23   
13    855/82dc1eceb2a9f3c76eb97d551898a430dd933fa7e5...      64      64   
14    416/980a99b0bb4021349fef8a8fea43819501e3d53dbd...     105     105   
15    814/07702cc039c2d36986c217c06a3ffeb4b9b4ff0ddd...      25      25   
16    493/858e5cf7648bc86749e728f173f31e8b900a23cdd6...      32      32   
17    506/34c9f10d9ec8cb5342e9d0f1f80c51f60eeaad2132...      24      24   
18    455/c9d6860afdf990f94f22f7075bd8c60e7586f8f6a9...      22      22   
19    412/1af64ca28362f58b93cb41739a484cb7689eb3a4c1...      28      28   
20    390/03c69be8d443b4bb5bf41b5a2471fd55a85fa28162...     118     118   
21    866/751b40bb32bb3a96024bf2a82244a012aded25fc19...      21      21   
22    828/5fbd14c6ed5991d107f95b96317562b67f54a8c013...      44      44   
23    348/7785d1d5b375192e1365b41145e5556ffb10277de7...      70      70   
24    426/94e3ef41607eb95f5c95c0c1815536c9c956083095...      61      61   
25    427/1186731feb5b7bf00b87fd47f4ef728ddf9e23de97...      29      29   
26    1279/b87a95e0f20e45ba6106acdd5664ab825c39df13e...      13      13   
27    416/ea9b47e47a24ab7d2ddacef5181307c77cc204309d...      40      40   
28    1057/3f6815f8c087b6989f2fb00fa8a478ce3091671ee...      42      42   
29    725/4c186d8b3ade60eb8782bee169a90cbc006d37377c...       7       7   
...                                                 ...     ...     ...   
3970  979/1cd98a89dd478bbb450d59276745ab817021da2bbd...      19      19   
3971  418/6a438652a8b4bfbd1329c32996a353f2f9f65d4763...      93      93   
3972  656/8b55c8ad9da43e9cffa2212244017861222e7baab3...      39      39   
3973  186/9fe8859211cb61b88d3440b6c9ce6100f6b5570637...       7       7   
3974  646/05ff8fae022eb0140c8446fc9e8dabf651c3f86fd5...      43      43   
3975  1034/1c8069a85241ebe284a44c28da4e9963882e77a97...      67      67   
3976  942/4099fd59bcf0b38bb38025fdc6ca03560f89066e25...      45      45   
3977  1008/415b95a0432d0b8ad2f1a529a56b2ff9b5c90fe5f...      22      22   
3978  1029/b6c7a926d9cdbf640ec50b44f6fc5cae5e37e4450...      33      33   
3979  1014/b890ab30dbecbdc97ea62d0b198712d830cceb679...     117     117   
3980  410/6eda4e7e1ab7c6831b3e1ea7c8468404c2b0ce3451...      79      79   
3981  963/662db3f657a8dd66a13a0a6a0325f879bcc249bf33...      23      23   
3982  468/fe82195143d107da9973e97ef4de9eec8701a5fa08...      25      25   
3983  488/463fd1e98beea4b55fd755b1ec1f286fb30f382eca...      78      78   
3984  872/13f72b2c1465fa7c1690dbeab95aa33cf5573a508b...      31      31   
3985  980/64d05e26d00b499308366a291d526d971cd17ca26f...      28      28   
3986  518/6795b97be9a1ddf1466dc73a02be4d4135c7824caf...      76      76   
3987  968/606de9c3409e875c847a14837cfa46fc42153bb708...      26      26   
3988  1033/7fdb78d0ff83e857299f01fd6fac24b05c913dcbb...      22      22   
3989  385/96d8485518af165b7285b54be793697f1d2f641b2f...      36      36   
3990  964/4f6483eeb169108feffed1af131d71807100b729d7...      27      27   
3991  314/91a11896c202ae06b7bb9de76522c856f30654ad0b...    

In [20]:
import os
image_names = os.listdir('Images/full_validation/unknown_class')

In [21]:
for i in range(len(image_names)):
    image_names[i] = image_names[i].replace('_','/')

In [24]:
true_labels = []
for name in image_names:
    temp = full_validation_set[full_validation_set['subDirectory_filePath'] == name]
    true_labels.append(temp.iloc[0]['expression'])


In [25]:
true_labels = np.array(true_labels)

In [68]:
from sklearn.metrics import accuracy_score, f1_score, cohen_kappa_score, confusion_matrix

In [32]:
top_1_score = accuracy_score(true_labels,top_1_pred)

In [33]:
top_1_score

0.53913478369592394

In [34]:
def get_top2_score(true_labels, top_2_pred):
    total = true_labels.shape[0]
    success = 0
    for i in range(total):
        if true_labels[i] in top_2_pred[i]:
            success += 1
    return success/total

In [35]:
top_2_score = get_top2_score(true_labels, top_2_pred)

In [36]:
top_2_score

0.75743935983996

In [63]:
f1_score_top_1 = f1_score(y_true=true_labels, y_pred=top_1_pred, average=None)

In [64]:
f1_score_top_1

array([ 0.49027895,  0.71490846,  0.57632933,  0.56570931,  0.60491071,
        0.43490701,  0.51762683,  0.23865546])

In [66]:
kappa_top_1 = cohen_kappa_score(true_labels, top_1_pred)

In [67]:
kappa_top_1

0.47328560797518648

In [80]:
confusion_mat = confusion_matrix(true_labels, top_1_pred, labels=[0,1,2,3,4,5,6,7])

In [81]:
confusion_mat

array([[290,  23,  61,  55,  11,   2,  52,   6],
       [ 23, 410,  10,  34,   2,   4,   6,  11],
       [ 58,   4, 336,  32,  12,   8,  48,   2],
       [ 39,  25,  31, 325,  54,   3,  22,   1],
       [ 22,   7,  57, 105, 271,   9,  29,   0],
       [ 44,  15,  71,  37,  24, 152, 154,   2],
       [ 62,   8,  62,  31,  19,  15, 301,   2],
       [145, 155,  38,  30,   3,   7,  51,  71]])